/*
 Name:    Highcharts
 Version: 1.2.2 (2010-03-04)
 Author:  Vevstein Web
 Support: www.highcharts.com/support
 License: www.highcharts.com/license
*/
(function(){function cc(a){if(!a||a.constructor!=Array)a=[a];return a}function Ta(a){return a!==ia&&a!==null}function ja(){var a=arguments,b,c;for(b=0;b<a.length;b++){c=a[b];if(Ta(c))return c}}function zb(a,b,c){var d,e="",f=c?"print":"",g=function(h){return R("style",{type:"text/css",media:h?"print":""},null,ra.getElementsByTagName("HEAD")[0])};dc||(dc=g());for(d in b)e+=Gb(d)+":"+b[d]+";";if(Ka){b=ra.styleSheets;c&&g(true);for(c=b.length-1;c>=0&&b[c].media!=f;)c--;f=b[c];f.addRule(a,e)}else dc.appendChild(ra.createTextNode(a+
" {"+e+"}\n"))}function K(a,b){a||(a={});for(var c in b)a[c]=b[c];return a}function Gc(a){return Ua=W(Ua,a)}function za(a){Hb||(Hb=R(Na));a&&Hb.appendChild(a);Hb.innerHTML=""}function db(a,b){var c=function(){};c.prototype=new a;K(c.prototype,b);return c}function Ab(a,b){if(typeof a=="string")return a;else if(a.linearGradient){var c=b.createLinearGradient.apply(b,a.linearGradient);o(a.stops,function(d){c.addColorStop(d[0],d[1])});return c}}function R(a,b,c,d,e){a=ra.createElement(a);b&&K(a,b);e&&
xa(a,{padding:0,border:"none",margin:0});c&&xa(a,c);d&&d.appendChild(a);return a}function xa(a,b){if(Ka)if(b.opacity!==ia)b.filter="alpha(opacity="+b.opacity*100+")";K(a.style,b)}function Hc(a,b,c,d){var e=Ua.lang;a=a;var f=isNaN(b=Aa(b))?2:b;b=c===ia?e.decimalPoint:c;d=d===ia?e.thousandsSep:d;e=a<0?"-":"";c=parseInt(a=Aa(+a||0).toFixed(f))+"";var g=(g=c.length)>3?g%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+Aa(a-c).toFixed(f).slice(2):"")}function rc(a,
b,c){function d(w){return w.toString().replace(/^([0-9])$/,"0$1")}if(!Ta(b))return"Invalid date";b=new Date(b*La);var e=b.getUTCHours(),f=b.getUTCDay(),g=b.getUTCDate(),h=b.getUTCMonth(),j=b.getUTCFullYear(),m=Ua.lang,s=m.weekdays;m=m.months;b={a:s[f].substr(0,3),A:s[f],d:d(g),e:g,b:m[h].substr(0,3),B:m[h],m:d(h+1),y:j.toString().substr(2,2),Y:j,H:d(e),I:d(e%12||12),l:e%12||12,M:d(b.getUTCMinutes()),p:e<12?"AM":"PM",P:e<12?"am":"pm",S:d(b.getUTCSeconds())};for(var x in b)a=a.replace("%"+x,b[x]);return c?
a.substr(0,1).toUpperCase()+a.substr(1):a}function Ib(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a.offsetParent;){a=a.offsetParent;b.x+=a.offsetLeft;b.y+=a.offsetTop;if(a!=ra.body&&a!=ra.documentElement){b.x-=a.scrollLeft;b.y-=a.scrollTop}}return b}function Ic(a){function b(l,i){var u;i=ja(i,true);ka(t,"addSeries",{options:l},function(){u=d(l);u.isDirty=true;t.isDirty=true;i&&t.redraw()});return u}function c(){var l=t.isDirty;o(ya,function(i){if(i.isDirty){i.cleanData();i.getSegments();if(i.options.legendType==
"point")l=true}});ub=null;if(Jb){o(Ga,function(i){i.setScale()});j();o(Ga,function(i){i.isDirty&&i.redraw()})}o(ya,function(i){i.isDirty&&i.redraw()});if(l){if(Kb.renderHTML){Kb.renderHTML(true);Kb.drawGraphics(true)}t.isDirty=false}mb&&mb.resetTracker&&mb.resetTracker();ka(t,"redraw")}function d(l){var i=l.type||C.defaultSeriesType,u=Jc[i],r=t.hasRendered;if(r)if(Oa&&i=="column")u=sc;else if(!Oa&&i=="bar")u=Lb;i=new u;i.init(t,l);if(!r&&i.inverted)Oa=true;ya.push(i);return i}function e(){var l=a.loading;
if(!nb){nb=R(Na,{className:"highcharts-loading"},K(l.style,{left:ca+F,top:P+F,width:ma+F,height:ga+F,zIndex:10,display:"none"}),la);R("span",{innerHTML:a.lang.loading},l.labelStyle,nb)}xa(nb,{display:""});vb(nb,{opacity:l.style.opacity},{duration:l.showDuration})}function f(){vb(nb,{opacity:0},{duration:a.loading.hideDuration,complete:function(){xa(nb,{display:"none"})}})}function g(l){var i,u,r;for(i=0;i<Ga.length;i++)if(Ga[i].options.id==l)return Ga[i];for(i=0;i<ya.length;i++)if(ya[i].options.id==
l)return ya[i];for(i=0;i<ya.length;i++){r=ya[i].data;for(u=0;u<r.length;u++)if(r[u].id==l)return r[u]}return null}function h(){var l=a.xAxis||{},i=a.yAxis||{},u;l=cc(l);o(l,function(r,M){r.index=M;r.isX=true});i=cc(i);o(i,function(r,M){r.index=M});Ga=l.concat(i);t.xAxis=[];t.yAxis=[];Ga=jb(Ga,function(r){u=new Bb(t,r);t[u.isXAxis?"xAxis":"yAxis"].push(u);return u});j()}function j(){C.alignTicks!==false&&o(Ga,function(l){l.adjustTickAmount()})}function m(){var l=[];o(ya,function(i){l=l.concat(Mb(i.data,
function(u){return u.selected}))});return l}function s(){return Mb(ya,function(l){return l.selected})}function x(l){t.toolbar.add("zoom","Reset zoom","Reset zoom level 1:1",function(){ka(t,"selection",{resetSelection:true},x);t.toolbar.remove("zoom")});!l||l.resetSelection?o(Ga,function(i){i.setExtremes(null,null,false)}):o(l.xAxis.concat(l.yAxis),function(i){var u=i.axis;if(t.tracker[u.isXAxis?"zoomX":"zoomY"])u.setExtremes(i.min,i.max,false)});c()}function w(){var l=a.title,i=a.subtitle;if(!t.titleLayer){var u=
new na("title-layer",la,null,{zIndex:2});l&&l.text&&R("h2",{className:"highcharts-title",innerHTML:l.text},l.style,u.div);i&&i.text&&R("h3",{className:"highcharts-subtitle",innerHTML:i.text},i.style,u.div);t.titleLayer=u}}function z(){var l=true;for(var i in t.resources)t.resources[i]||(l=false);l&&A()}function A(){h();o(ya,function(l){l.translate();l.setTooltipPoints();a.tooltip.enabled&&l.createArea()});t.render=oa;setTimeout(function(){oa();ka(t,"load")},0)}function S(){Pa=C.renderTo;ec="highcharts-"+
fc++;if(typeof Pa=="string")Pa=ra.getElementById(Pa);Pa.innerHTML="";if(!Pa.offsetWidth){kb=Pa.cloneNode(0);xa(kb,{position:sa,top:"-9999px",display:""});ra.body.appendChild(kb)}var l=(kb||Pa).offsetHeight;eb=C.width||(kb||Pa).offsetWidth||600;Da=C.height||(l>P+ob?l:0)||400;la=R(Na,{className:"highcharts-container"+(C.className?" "+C.className:""),id:ec},K({position:Nb,overflow:Va,width:eb+F,height:Da+F,textAlign:"left"},C.style),kb||Pa)}function oa(){var l,i=a.labels,u=a.credits;l=2*(C.borderWidth||
0)+(C.shadow?8:0);tc.drawRect(l/2,l/2,eb-l,Da-l,C.borderColor,C.borderWidth,C.borderRadius,C.backgroundColor,C.shadow);tc.drawRect(ca,P,ma,ga,null,null,null,C.plotBackgroundColor,null,Ob);(new na("plot-border",la,null,{zIndex:4})).drawRect(ca,P,ma,ga,C.plotBorderColor,C.plotBorderWidth,null,null,C.plotShadow);Ka&&zb(".highcharts-image-map",{display:"none"},"print");Jb&&o(Ga,function(r){r.render()});w();i.items&&o(i.items,function(){var r=K({className:"highcharts-label"},this.attributes);gc.drawHtml(this.html,
r,K(i.style,this.style))});o(ya,function(r){r.render()});Kb=t.legend=new ta(t);if(!t.toolbar)t.toolbar=fb(t);if(u.enabled&&!t.credits)t.credits=R("a",{className:"highcharts-credits",href:u.href,innerHTML:u.text,target:u.target},K(u.style,{zIndex:8}),la);t.hasRendered=true;if(kb){Pa.appendChild(la);za(kb);Wa=Ib(la)}}function pa(){function l(i){var u=i.attributes,r,M;if(u){r=u.length;for(r=r-1;r>=0;r-=1){M=u[r].name;if(typeof i[M]!="object")i[M]=null}}if(u=i.childNodes){r=u.length;for(r=r-1;r>=0;r--){u=
i.childNodes[r];l(u);u.childNodes.length||za(u)}}}o(ya,function(i){i.destroy()});l(la)}function Bb(l,i){function u(){i=W(ua?Pb:hc,da?Ba?Kc:uc:Ba?Lc:Mc,i)}function r(){var k=[],p;Ha=Ma=null;Qb=[];o(ya,function(v){p=false;o(["xAxis","yAxis"],function(I){if((I=="xAxis"&&ua||I=="yAxis"&&!ua)&&(v.options[I]==i.index||v.options[I]===ia&&i.index==0)){v[I]=Xa;Qb.push(v);p=true}});if(!v.visible&&C.ignoreHiddenSeries)p=false;if(p){var y;if(!ua){y=v.options.stacking;Rb=y=="percent";if(y){var D=k[v.type]||[];
k[v.type]=D}if(Rb){Ha=0;Ma=99}}if(v.isCartesian){Jb=true;o(v.data,function(I){var G=I.x,H=I.y;if(Ha===null)Ha=Ma=I[Sb];if(ua)if(G>Ma)Ma=G;else{if(G<Ha)Ha=G}else if(Ta(H)){if(y)D[G]=D[G]?D[G]+H:H;I=D?D[G]:H;if(!Rb)if(I>Ma)Ma=I;else if(I<Ha)Ha=I;if(y)Ya[v.type][G]={total:I,cum:I}}});if(!ua&&/(area|column|bar)/.test(v.type))if(Ha>=0){Ha=0;vc=true}else if(Ma<0){Ma=0;wc=true}}}})}function M(k,p,v){var y=1,D=0;if(v){y*=-1;D=Cb}if(pb){y*=-1;D-=y*Cb}if(p){if(pb)k=Cb-k;k=k/qb+T}else k=y*(k-T)*qb+D;return k}
function ha(k,p,v){if(v){var y,D,I;y=M(k);var G;k=D=y+Tb;y=I=Da-y-Tb;if(da){y=P;I=Da-ob;if(k<ca||k>ca+ma)G=true}else{k=ca;D=eb-wb;if(y<P||y>P+ga)G=true}G||xc.drawLine(k,y,D,I,p,v)}}function va(k,p,v){k=Ub(k,T);p=Math.min(p,ea);var y=(p-k)*qb;ha(k+(p-k)/2,v,y)}function B(k,p,v,y,D,I,G){var H,Za,Z,L=i.labels;if(p=="inside")D=-D;if(Ba)D=-D;p=Za=M(k+rb)+Tb;H=Z=Da-M(k+rb)-Tb;if(da){H=Da-ob-(Ba?ga:0)+lb;Z=H+D}else{p=ca+(Ba?ma:0)+lb;Za=p-D}y&&xb.drawLine(p,H,Za,Z,v,y);if(I&&L.enabled)if((k=Vb.call({index:G,
isFirst:k==aa[0],isLast:k==aa[aa.length-1],value:Ea&&Ea[k]?Ea[k]:k}))||k===0)xb.addText(k,p+L.x-(rb&&da?rb*qb*(pb?-1:1):0),H+L.y-(rb&&!da?rb*qb*(pb?1:-1):0),L.style,L.rotation,L.align)}function fa(k,p){var v;ja(i.allowDecimals,true);Db=p?1:wa.pow(10,Qa(wa.log(k)/wa.LN10));v=k/Db;p||(p=[1,2,2.5,5,10]);for(var y=0;y<p.length;y++){k=p[y];if(v<=(p[y]+(p[y+1]||p[y]))/2)break}k*=Db;return k}function Q(){aa=[];for(var k=1E3/La,p=6E4/La,v=36E5/La,y=864E5/La,D=6048E5/La,I=2592E6/La,G=31556952E3/La,H=[["second",
k,[1,2,5,10,15,30]],["minute",p,[1,2,5,10,15,30]],["hour",v,[1,2,3,4,6,8,12]],["day",y,[1,2]],["week",D,[1,2]],["month",I,[1,2,3,4,6]],["year",G,null]],Za=H[6],Z=Za[1],L=Za[2],$a=0;$a<H.length;$a++){Za=H[$a];Z=Za[1];L=Za[2];if(H[$a+1]){var Nc=(Z*L[L.length-1]+H[$a+1][1])/2;if(Fa<=Nc)break}}if(Z==G&&Fa<5*Z)L=[1,2,5];H=fa(Fa/Z,L);var sb;L=new Date(T*La);L.setUTCMilliseconds(0);if(Z>=k)L.setUTCSeconds(Z>=p?0:H*Qa(L.getUTCSeconds()/H));if(Z>=p)L.setUTCMinutes(Z>=v?0:H*Qa(L.getUTCMinutes()/H));if(Z>=v)L.setUTCHours(Z>=
y?0:H*Qa(L.getUTCHours()/H));if(Z>=y)L.setUTCDate(Z>=I?1:H*Qa(L.getUTCDate()/H));if(Z>=I){L.setUTCMonth(Z>=G?0:H*Qa(L.getUTCMonth()/H));sb=L.getUTCFullYear()}if(Z>=G){sb-=sb%H;L.setUTCFullYear(sb)}Z==D&&L.setUTCDate(L.getUTCDate()-L.getUTCDay()+i.startOfWeek);$a=1;k=L.getTime()/La;sb=L.getUTCFullYear();for(p=L.getUTCMonth();k<ea&&$a<ma;){aa.push(k);if(Z==G)k=Date.UTC(sb+$a*H,0)/La;else if(Z==I)k=Date.UTC(sb,p+$a*H)/La;else k+=Z*H;$a++}aa.push(k);i.labels.formatter||(Vb=function(){return rc(i.dateTimeLabelFormats[Za[0]],
this.value,1)})}function U(){var k=function(y){var D=(Db<1?1/Db:1)*10;return N(y*D)/D},p;p=Qa(T/Fa)*Fa;var v=wa.ceil(ea/Fa)*Fa;aa=[];for(p=k(p);p<=v;){aa.push(p);p=k(p+Fa)}if(Ea){T-=0.5;ea+=0.5}Vb||(Vb=function(){return this.value})}function X(){Wb?Q():U();var k=aa[0],p=aa[aa.length-1];if(i.startOnTick)T=k;else T>k&&aa.shift();if(i.endOnTick)ea=p;else ea<p&&aa.pop()}function Ca(){if(!Wb&&!Ea){var k=yb,p=aa.length;yb=ub[Sb];if(p<yb){for(;aa.length<yb;)aa.push(aa[aa.length-1]+Fa);qb*=(p-1)/(yb-1)}if(Ta(k)&&
yb!=k)Xa.isDirty=true}}function q(){var k,p,v,y=T,D=ea;k=i.maxZoom;var I;r();T=ja(yc,i.min,Ha);ea=ja(zc,i.max,Ma);if(ea-T<k){I=(k-ea+T)/2;T=Ub(T-I,ja(i.min,T-I));ea=wa.min(T+k,ja(i.max,T+k))}if(!Ea&&!Rb){k=ea-T||1;if(!Ta(i.min)&&Ac&&(Ha<0||!vc))T-=k*Ac;if(!Ta(i.max)&&Bc&&(Ma>0||!wc))ea+=k*Bc}Fa=Ea||T==ea?1:i.tickInterval=="auto"?(ea-T)*i.tickPixelInterval/Cb:i.tickInterval;Wb||(Fa=fa(Fa));ic=i.minorTickInterval=="auto"&&Fa?Fa/5:i.minorTickInterval;X();qb=Cb/(ea-T||1);ub||(ub={x:0,y:0});if(!Wb&&aa.length>
ub[Sb])ub[Sb]=aa.length;if(!ua)for(p in Ya)for(v in Ya[p])Ya[p][v].cum=Ya[p][v].total;Xa.isDirty=T!=y||ea!=D}function Y(k,p,v){v=ja(v,true);ka(Xa,"setExtremes",{min:k,max:p},function(){if(Ea){if(k<0)k=0;if(p>Ea.length-1)p=Ea.length-1}yc=k;zc=p;v&&l.redraw()})}function E(k,p){Ea=k;ja(p,true)&&Ra()}function n(){return{min:T,max:ea,dataMin:Ha,dataMax:Ma}}function J(k){var p=k.width,v=p?jc:kc;v.push(k);p?ha(k.value,k.color,k.width):va(k.from,k.to,k.color)}function ba(k){o([kc,jc],function(p){for(var v=
0;v<p.length;v++)if(p[v].id==k){p.splice(v,1);break}});gb()}function Ra(){mb.resetTracker&&mb.resetTracker();gb();o(Qb,function(k){k.isDirty=true})}function gb(){var k=i.title,p=i.alternateGridColor,v=i.minorTickWidth,y=i.lineWidth,D,I;xb.clear();xc.clear();if(!(!Qb.length||!Ta(T)||!Ta(ea))){p&&o(aa,function(G,H){if(H%2==0&&G<ea)va(G,aa[H+1]!==ia?aa[H+1]:ea,p)});o(kc,function(G){va(G.from,G.to,G.color)});if(ic&&!Ea)for(D=T;D<=ea;D+=ic){ha(D,i.minorGridLineColor,i.minorGridLineWidth);v&&B(D,i.minorTickPosition,
i.minorTickColor,v,i.minorTickLength)}o(aa,function(G,H){I=G+rb;ha(I,i.gridLineColor,i.gridLineWidth);B(G,i.tickPosition,i.tickColor,i.tickWidth,i.tickLength,!(G==T&&!i.showFirstLabel||G==ea&&!i.showLastLabel),H)});o(jc,function(G){ha(G.value,G.color,G.width)});if(y){v=ca+(Ba?ma:0)+lb;D=Da-ob-(Ba?ga:0)+lb;xb.drawLine(da?ca:v,da?D:P,da?eb-wb:v,da?D:Da-ob,i.lineColor,y)}if(k&&k.enabled&&k.text){y=da?ca:P;v=da?ma:ga;y={low:y+(da?0:v),middle:y+v/2,high:y+(da?v:0)}[k.align];v=(da?P+ga:ca)+(da?1:-1)*(Ba?
-1:1)*k.margin-(Ka?parseInt(k.style.fontSize||k.style.font.replace(/^[a-z ]+/,""))/3:0);xb.addText(k.text,da?y:v+(Ba?ma:0)+lb,da?v-(Ba?ga:0)+lb:y,k.style,k.rotation||0,{low:"left",middle:"center",high:"right"}[k.align])}xb.strokeText();Xa.isDirty=false}}var ua=i.isX,Ba=i.opposite,da=Oa?!ua:ua,Ya={bar:{},column:{},area:{},areaspline:{}};u();var Xa=this,Wb=i.type=="datetime",lb=i.offset||0,Sb=ua?"x":"y",Cb=da?ma:ga,qb,Tb=da?ca:ob,xb=new na("axis-layer",la,null,{zIndex:7}),xc=new na("grid-layer",la,
null,{zIndex:1}),Ha,Ma,Qb,yc,zc,ea=null,T=null,Ac=i.minPadding,Bc=i.maxPadding,vc,wc,Rb,Cc=i.events,lc,kc=i.plotBands||[],jc=i.plotLines||[],Fa,ic,Db,aa,yb,Vb=i.labels.formatter,Ea=i.categories||ua&&l.columnCount,pb=i.reversed,rb=Ea&&i.tickmarkPlacement=="between"?0.5:0;if(Oa&&ua&&pb===ia)pb=true;Ba||(lb*=-1);if(da)lb*=-1;K(Xa,{addPlotBand:J,addPlotLine:J,adjustTickAmount:Ca,categories:Ea,getExtremes:n,isXAxis:ua,options:i,render:gb,setExtremes:Y,setScale:q,setCategories:E,translate:M,redraw:Ra,removePlotBand:ba,
removePlotLine:ba,reversed:pb,stacks:Ya});for(lc in Cc)Ia(Xa,lc,Cc[lc]);q()}function fb(){function l(M,ha,va,B){if(!r[M]){ha=R(Na,{innerHTML:ha,title:va,onclick:B},K(a.toolbar.itemStyle,{zIndex:1003}),u.div);r[M]=ha}}function i(M){za(r[M]);r[M]=null}var u,r={};u=new na("toolbar",la,null,{zIndex:1004,width:"auto",height:"auto"});return{add:l,remove:i}}function ab(l,i){function u(n){n=n||Sa.event;if(!n.target)n.target=n.srcElement;if(!n.pageX)n.pageX=n.clientX+(ra.documentElement.scrollLeft||ra.body.scrollLeft);
if(!n.pageY)n.pageY=n.clientY+(ra.documentElement.scrollTop||ra.body.scrollTop);return n}function r(n){var J={xAxis:[],yAxis:[]};o(Ga,function(ba){var Ra=ba.translate,gb=ba.isXAxis,ua=Oa?!gb:gb;J[gb?"xAxis":"yAxis"].push({axis:ba,value:Ra(ua?n.pageX-Wa.x-ca:ga-n.pageY+Wa.y+P,true)})});return J}function M(){bb.onmousedown=function(n){n=u(n);n.preventDefault&&n.preventDefault();l.mouseIsDown=Eb=true;U=n.pageX;X=n.pageY;if(Jb&&(Y||E)){q||(q=R(Na,null,{position:sa,border:"none",background:"#4572A7",opacity:0.25,
width:Y?0:ma+F,height:E?0:ga+F}));gc.div.appendChild(q)}};bb.onmousemove=function(n){n=u(n);n.returnValue=false;if(Eb){Ca=Math.sqrt(Math.pow(U-n.pageX,2)+Math.pow(X-n.pageY,2))>10;if(Y){var J=n.pageX-U;xa(q,{width:Aa(J)+F,left:(J>0?0:J)+U-Wa.x-ca+F})}if(E){n=n.pageY-X;xa(q,{height:Aa(n)+F,top:(n>0?0:n)+ +X-Wa.y-P+F})}}else ha(n);return false};bb.onmouseup=function(){var n;if(q){var J={xAxis:[],yAxis:[]},ba=q.offsetLeft,Ra=q.offsetTop,gb=q.offsetWidth,ua=q.offsetHeight;if(Ca){o(Ga,function(Ba){var da=
Ba.translate,Ya=Ba.isXAxis,Xa=Oa?!Ya:Ya;J[Ya?"xAxis":"yAxis"].push({axis:Ba,min:da(Xa?ba:ga-Ra-ua,true),max:da(Xa?ba+gb:ga-Ra,true)})});ka(l,"selection",J,x);n=true}za(q);q=null}l.mouseIsDown=Eb=Ca=false};bb.onmouseout=function(n){n=n||Sa.event;if((n=n.relatedTarget||n.toElement)&&n!=Xb&&n.tagName!="AREA"){B();l.mouseIsDown=Eb=Ca=false}};bb.onclick=function(n){n=u(n);n.cancelBubble=true;if(!Ca)if(Q&&n.target.tagName=="AREA"){var J=Q.plotX,ba=Q.plotY;K(Q,{pageX:Wa.x+ca+(Oa?ma-ba:J),pageY:Wa.y+P+(Oa?
ga-J:ba)});ka(l.hoverSeries,"click",K(n,{point:Q}));Q.firePointEvent("click",n)}else{K(n,r(n));ka(l,"click",n)}Ca=false}}function ha(n){var J=l.hoverPoint,ba=l.hoverSeries;if(ba){J||(J=ba.tooltipPoints[Oa?n.pageY-Wa.y-P:n.pageX-Wa.x-ca]);if(J&&J!=Q){Q&&Q.firePointEvent("mouseOut");J.firePointEvent("mouseOver");Yb.refresh(J);Q=J}}}function va(){var n="highchartsMap"+Oc++;l.imagemap=bb=R("map",{name:n,id:n,className:"highcharts-image-map"},null,la);Xb=R("img",{useMap:"#"+n},{width:ma+F,height:ga+F,
left:ca+F,top:P+F,opacity:0,border:"none",position:sa,clip:"rect(1px,"+ma+"px,"+ga+"px,1px)",zIndex:9},bb);if(!Ka)Xb.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="}function B(){Yb.hide();if(l.hoverSeries){l.hoverSeries.setState();Q=l.hoverSeries=null}}function fa(n){var J=0,ba,Ra=bb.childNodes;for(ba=0;ba<Ra.length;ba++)if(Ra[ba].isLegendArea){J=ba+1;break}bb.insertBefore(n,Ra[J])}if(i.enabled){var Q,U,X,Ca,q,Y=/x/.test(l.options.chart.zoomType),E=/y/.test(l.options.chart.zoomType);
va();l.tooltip=Yb=hb(i);M();setInterval(function(){mc&&mc()},32);K(this,{insertAtFront:fa,zoomX:Y,zoomY:E,resetTracker:B})}}function hb(l){function i(fa,Q){var U=fa.tooltipPos;Q=fa.series;var X=l.borderColor||fa.color||Q.color||"#606060",Ca=t.inverted,q,Y,E,n=ha.offsetHeight;E=fa.tooltipText;M=Q;q=U?U[0]:Ca?ma-fa.plotY:fa.plotX;U=U?U[1]:Ca?ga-fa.plotX:fa.plotY;if(q>=0&&q<=ma&&U>=0&&U<=ga)Y=true;if(E===false||!Y)r();else{ha.innerHTML=E;Y=ha.offsetWidth-va;E=ha.offsetHeight-va;if(Y>(B.w||0)+20||Y<(B.w||
0)-20||E>B.h||B.c!=X||n!=ha.offsetHeight){B.clear();B.drawRect(va/2,va/2,Y+20,E,X,va,l.borderRadius,l.backgroundColor,l.shadow);K(B,{w:Y,h:E,c:X})}X=q-B.w+ca-35;q=U-B.h+10+P;if(X<5){X=5;q-=20}if(q<5)q=5;else if(q+B.h>Da)q=Da-B.h-5;u(N(X),N(q));Q.drawPointState(fa,"hover");cb.style.visibility=nc}}function u(fa,Q){var U=cb.style.visibility==Va,X=U?fa:(cb.offsetLeft+fa)/2;U=U?Q:(cb.offsetTop+Q)/2;xa(cb,{left:X+F,top:U+F});mc=Aa(fa-X)>1||Aa(Q-U)>1?function(){u(fa,Q)}:null}function r(){if(cb)cb.style.visibility=
Va;M&&M.drawPointState()}var M,ha,va=l.borderWidth,B;cb=R(Na,null,{position:sa,visibility:Va,overflow:Va,padding:"0 50px 5px 0",zIndex:8},la);B=new na("tooltip-box",cb,null,{width:eb+F,height:Da+F});ha=R(Na,{className:"highcharts-tooltip"},K(l.style,{maxWidth:eb-40+F,overflow:Va,textOverflow:"ellipsis",position:Nb,zIndex:2}),cb);return{refresh:i,hide:r}}var ta=function(l){function i(Ca){if(Ca){o(Q,function(q){za(q.legendItem)});Q=[]}o(l.series,function(q){if(q.options.showInLegend){var Y=q.options.legendType==
"point"?q.data:[q];o(Y,function(E){E.simpleSymbol=/(bar|pie|area|column)/.test(q.type);E.legendItem=M=R("li",{innerHTML:r.labelFormatter.call(E),className:E.visible?"":Fb},null,B.firstChild);if(E.options&&E.options.showCheckbox)E.checkbox=R("input",{type:"checkbox",checked:E.selected,defaultChecked:E.selected},r.itemCheckboxStyle,M);Ia(M,"mouseover",function(){E.setState("hover")});Ia(M,"mouseout",function(){E.setState()});Ia(M,"click",function(n){n=n.target;var J="legendItemClick",ba=function(){E.setVisible()};
if(n.tagName=="INPUT")ka(E,"checkboxClick",{checked:n.checked},function(){E.select()});else E.firePointEvent?E.firePointEvent(J,null,ba):ka(E,J,null,ba)});Q.push(E)})}})}function u(Ca){if(Ca){U.clear();za(X);X=null}if(ya.length){if(r.borderWidth||r.backgroundColor)U.drawRect(B.offsetLeft,B.offsetTop,B.offsetWidth,B.offsetHeight,r.borderColor,r.borderWidth,r.borderRadius,r.backgroundColor,r.shadow);o(Q,function(q){if(q.legendItem){var Y=q.legendItem,E=B.offsetLeft+Y.offsetLeft;Y=B.offsetTop+Y.offsetTop+
Y.offsetHeight/2;var n=q.legendItem.className==Fb,J=n?r.itemHiddenStyle.color:q.color;!q.simpleSymbol&&q.options&&q.options.lineWidth&&U.drawLine(E,Y,E+va,Y,J,q.options.lineWidth);if(q.simpleSymbol)U.drawRect(E,Y-6,16,12,null,0,2,J);else if(q.options&&q.options.marker&&q.options.marker.enabled)q.drawMarker(U,E+va/2,Y,W(q.options.marker,n?{fillColor:J,lineColor:J}:null))}});if(bb){X=R("area",{shape:"rect",isLegendArea:true,coords:[B.offsetLeft-ca,B.offsetTop-P,B.offsetLeft+B.offsetWidth-ca,B.offsetTop+
B.offsetHeight-P].join(",")});mb.insertAtFront(X);X.onmouseover=function(q){q=q||Sa.event;q=q.relatedTarget||q.fromElement;if(q!=B&&!Eb){Yb.hide();xa(B,{zIndex:10})}};B.onmouseout=X.onmouseout=function(q){q=q||Sa.event;if((q=q.relatedTarget||q.toElement)&&(q==Xb||q.tagName=="AREA"&&q!=X))xa(B,{zIndex:7})}}}}var r=l.options.legend;if(r.enabled){var M,ha=r.layout,va=r.symbolWidth,B,fa="#"+la.id+" .highcharts-legend li",Q=[],U=new na("legend",la,null,{zIndex:7}),X;this.dom=B=R(Na,{className:"highcharts-legend highcharts-legend-"+
ha,innerHTML:'<ul style="margin:0;padding:0"></ul>'},K({position:sa,zIndex:7},r.style),la);zb(fa,K(r.itemStyle,{paddingLeft:va+r.symbolPadding+F,"float":ha=="horizontal"?"left":"none"}));zb(fa+":hover",r.itemHoverStyle);zb(fa+"."+Fb,r.itemHiddenStyle);zb(".highcharts-legend-horizontal li",{"float":"left"});i();u();return{renderHTML:i,drawGraphics:u}}};Pb=W(Pb,Ua.xAxis);hc=W(hc,Ua.yAxis);Ua.xAxis=Ua.yAxis=null;a=W(Ua,a);var C=a.chart,V=C.margin;V=typeof V=="number"?[V,V,V,V]:V;var P=V[0],wb=V[1],ob=
V[2],ca=V[3],Pa,kb,la,ec,eb,Da;S();var t=this;V=C.events;var oc,bb,Yb,Eb,tc=new na("chart-background",la),nb,gc,ga,ma,mb,Xb,Kb,Wa=Ib(la),Jb,Ga=[],ub,ya=[],Ob,Oa,mc,cb,Jc={line:Pc,spline:Dc,area:Qc,areaspline:Rc,column:Lb,bar:sc,pie:Sc,scatter:Tc};Zb=tb=0;Ia(Sa,"resize",function(){var l=ra.getElementById(ec);if(l)Wa=Ib(l)});Ia(Sa,"unload",pa);if(V)for(oc in V)Ia(t,oc,V[oc]);t.addLoading=function(l){t.resources[l]=false};t.clearLoading=function(l){t.resources[l]=true;z()};t.options=a;t.series=ya;t.resources=
{};t.inverted=Oa=a.chart.inverted;t.chartWidth=eb;t.chartHeight=Da;t.plotWidth=ma=eb-ca-wb;t.plotHeight=ga=Da-P-ob;t.plotLeft=ca;t.plotTop=P;t.redraw=c;t.addSeries=b;t.getSelectedPoints=m;t.getSelectedSeries=s;t.showLoading=e;t.hideLoading=f;t.get=g;t.destroy=pa;t.updatePosition=Ib;t.plotLayer=gc=new na("plot",la,null,{position:sa,width:ma+F,height:ga+F,left:ca+F,top:P+F,overflow:Va,zIndex:3});t.tracker=mb=new ab(t,a.tooltip);if(C.plotBackgroundImage){t.addLoading("plotBack");Ob=R("img");Ob.onload=
function(){t.clearLoading("plotBack")};Ob.src=C.plotBackgroundImage}o(a.series,function(l){d(l)});z()}function Ec(a){for(var b=[],c=[],d=0;d<a.length;d++){b[d]=a[d].plotX;c[d]=a[d].plotY}this.xdata=b;this.ydata=c;a=[];this.y2=[];var e=c.length;this.n=e;this.y2[0]=0;this.y2[e-1]=0;a[0]=0;for(d=1;d<e-1;d++){var f=b[d+1]-b[d-1];f=(b[d]-b[d-1])/f;var g=f*this.y2[d-1]+2;this.y2[d]=(f-1)/g;a[d]=(c[d+1]-c[d])/(b[d+1]-b[d])-(c[d]-c[d-1])/(b[d]-b[d-1]);a[d]=(6*a[d]/(b[d+1]-b[d-1])-f*a[d-1])/g}for(b=e-2;b>=
0;b--)this.y2[b]=this.y2[b]*this.y2[b+1]+a[b]}var ia,ra=document,Sa=window,wa=Math,N=wa.round,Qa=wa.floor,Ub=wa.max,Aa=wa.abs,$b=wa.cos,ac=wa.sin,O=navigator.userAgent,Ka=/msie/i.test(O)&&!Sa.opera,Uc=/AppleWebKit/.test(O),dc,Oc=0,tb,Zb,Fc={},fc=0,La=1,Hb,Na="div",sa="absolute",Nb="relative",Va="hidden",Fb="highcharts-"+Va,nc="visible",F="px",qa=(O=Sa.HighchartsAdapter)||{},o=qa.each,Mb=qa.grep,jb=qa.map,W=qa.merge,Gb=qa.hyphenate,Ia=qa.addEvent,ka=qa.fireEvent,vb=qa.animate,pc=qa.getAjax;if(!O&&
Sa.jQuery){var ib=jQuery;o=function(a,b){for(var c=0,d=a.length;c<d;c++)if(b.call(a[c],a[c],c,a)===false)return c};Mb=ib.grep;jb=function(a,b){for(var c=[],d=0,e=a.length;d<e;d++)c[d]=b.call(a[d],a[d],d,a);return c};W=function(){var a=arguments;return ib.extend(true,null,a[0],a[1],a[2],a[3])};Gb=function(a){return a.replace(/([A-Z])/g,function(b,c){return"-"+c.toLowerCase()})};Ia=function(a,b,c){ib(a).bind(b,c)};ka=function(a,b,c,d){var e=ib.Event(b),f="detached"+b;K(e,c);if(a[b]){a[f]=a[b];a[b]=
null}ib(a).trigger(e);if(a[f]){a[b]=a[f];a[f]=null}d&&!e.isDefaultPrevented()&&d(e)};vb=function(a,b,c){ib(a).animate(b,c)};pc=function(a,b){ib.get(a,null,b)};ib.extend(ib.easing,{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}})}else if(!O&&Sa.MooTools){o=$each;jb=function(a,b){return a.map(b)};Mb=function(a,b){return a.filter(b)};W=$merge;Gb=function(a){return a.hyphenate()};Ia=function(a,b,c){if(!a.addEvent)if(a.nodeName)a=$(a);else K(a,new Events);a.addEvent(b,c)};ka=function(a,b,c,d){b=
new Event({type:b,target:a});b=K(b,c);b.preventDefault=function(){d=null};a.fireEvent&&a.fireEvent(b.type,b);d&&d(b)};vb=function(a,b,c){a=new Fx.Morph($(a),K(c,{transition:Fx.Transitions.Quad.easeInOut}));a.start(b)};pc=function(a,b){(new Request({url:a,method:"get",onSuccess:b})).send()}}O='normal 12px "Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif';qa={enabled:true,align:"center",x:0,y:15,style:{color:"#666",font:O.replace("12px","11px")}};var Ua={colors:["#4572A7",
"#AA4643","#89A54E","#80699B","#3D96AE","#DB843D","#92A8CD","#A47D7C","#B5CA92"],symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:["January","February","March","April","May","June","July","August","September","October","November","December"],weekdays:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],decimalPoint:".",thousandsSep:","},chart:{margin:[50,50,60,80],borderColor:"#4572A7",borderRadius:5,defaultSeriesType:"line",ignoreHiddenSeries:true,
plotBorderColor:"#C0C0C0"},title:{text:"Chart title",style:{textAlign:"center",color:"#3E576F",font:O.replace("12px","16px"),margin:"10px 0 0 0"}},subtitle:{text:"",style:{textAlign:"center",color:"#6D869F",font:O,margin:0}},plotOptions:{line:{allowPointSelect:false,showCheckbox:false,animation:true,events:{},lineWidth:2,shadow:true,marker:{enabled:true,symbol:"auto",lineWidth:0,radius:4,lineColor:"#FFFFFF",fillColor:"auto",states:{hover:{},select:{fillColor:"#FFFFFF",lineColor:"auto",lineWidth:2}}},
point:{events:{}},dataLabels:W(qa,{enabled:false,y:-6,formatter:function(){return this.y}}),showInLegend:true,states:{hover:{lineWidth:3,marker:{}},select:{marker:{}}}}},labels:{style:{position:sa,color:"#3E576F",font:O}},legend:{enabled:true,layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:5,shadow:true,style:{bottom:"10px",left:"80px",padding:"5px"},itemStyle:{listStyle:"none",margin:0,padding:"0 2em 0 0",font:O,cursor:"pointer",color:"#3E576F",
position:Nb},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:sa,right:0},symbolWidth:16,symbolPadding:5},loading:{hideDuration:100,labelStyle:{font:O.replace("normal","bold"),position:Nb,top:"1em"},showDuration:100,style:{position:sa,backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:true,formatter:function(){return"<b>"+(this.point.name||this.series.name)+"</b><br/>X value: "+this.x+"<br/>Y value: "+this.y},backgroundColor:"rgba(255, 255, 255, .85)",
borderWidth:2,borderRadius:5,shadow:true,snap:10,style:{color:"#333333",font:O,fontSize:"9pt",padding:"5px",whiteSpace:"nowrap"}},toolbar:{itemStyle:{color:"#4572A7",cursor:"pointer",margin:"20px",font:O}},credits:{enabled:true,text:"Highcharts.com",href:"http://www.highcharts.com",style:{position:sa,right:"10px",bottom:"5px",color:"#999",textDecoration:"none",font:O.replace("12px","10px")},target:"_self"}},Pb={dateTimeLabelFormats:{second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",
month:"%b '%y",year:"%Y"},endOnTick:false,gridLineColor:"#C0C0C0",labels:qa,lineColor:"#C0D0E0",lineWidth:1,max:null,min:null,maxZoom:null,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",minorTickWidth:1,showFirstLabel:true,showLastLabel:false,startOfWeek:1,startOnTick:false,tickColor:"#C0D0E0",tickInterval:"auto",tickLength:5,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{enabled:false,
text:"X-values",align:"middle",margin:35,style:{color:"#6D869F",font:O.replace("normal","bold")}},type:"linear"},hc=W(Pb,{endOnTick:true,gridLineWidth:1,tickPixelInterval:72,showLastLabel:true,labels:{align:"right",x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:true,tickWidth:0,title:{enabled:true,margin:40,rotation:270,text:"Y-values"}}),Mc={labels:{align:"right",x:-8,y:3},title:{rotation:270}},Lc={labels:{align:"left",x:8,y:3},title:{rotation:90}},uc={labels:{align:"center",x:0,
y:14},title:{rotation:0}},Kc=W(uc,{labels:{y:-5}});O=Ua.plotOptions;qa=O.line;O.spline=W(qa);O.scatter=W(qa,{lineWidth:0,states:{hover:{lineWidth:0}}});O.area=W(qa,{fillColor:"auto"});O.areaspline=W(O.area);O.column=W(qa,{borderColor:"#FFFFFF",borderWidth:1,borderRadius:0,groupPadding:0.2,pointPadding:0.1,states:{hover:{brightness:0.1,shadow:false},select:{color:"#C0C0C0",borderColor:"#000000",shadow:false}}});O.bar=W(O.column,{dataLabels:{align:"left",x:5,y:0}});O.pie=W(qa,{borderColor:"#FFFFFF",
borderWidth:1,center:["50%","50%"],legendType:"point",size:"90%",slicedOffset:10,states:{hover:{brightness:0.1,shadow:false}}});var qc=function(a){function b(h){if(g=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]+(?:\.[0-9]+)?)\s*\)/.exec(h))f=[parseInt(g[1]),parseInt(g[2]),parseInt(g[3]),parseFloat(g[4])];else if(g=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(h))f=[parseInt(g[1],16),parseInt(g[2],16),parseInt(g[3],16),1]}function c(){return f&&!isNaN(f[0])?
"rgba("+f.join(",")+")":a}function d(h){if(typeof h=="number"&&h!=0)for(var j=0;j<3;j++){f[j]+=parseInt(h*255);if(f[j]<0)f[j]=0;if(f[j]>255)f[j]=255}return this}function e(h){f[3]=h;return this}var f=[],g;b(a);return{get:c,brighten:d,setOpacity:e}},na=function(a,b,c,d){var e=this,f=b.style;c=K({className:"highcharts-"+a},c);d=K({width:f.width,height:f.height,position:sa,top:0,left:0,margin:0,padding:0,border:"none"},d);a=R(Na,c,d,b);K(e,{div:a,width:parseInt(d.width),height:parseInt(d.height)});e.svg=
Ka?"":'<?xml version="1.0" encoding="utf-8"?><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="'+e.width+'px" height="'+e.height+'">';e.basicSvg=e.svg};na.prototype={getCtx:function(){if(!this.ctx){var a=R("canvas",{id:"highcharts-canvas-"+fc++,width:this.width,height:this.height},{position:sa},this.div);if(Ka){G_vmlCanvasManager.initElement(a);a=ra.getElementById(a.id)}this.ctx=a.getContext("2d")}return this.ctx},getSvg:function(){if(!this.svgObject){var a=
this,b=a.div,c=a.width;a=a.height;if(Ka){if(!ra.namespaces.g_vml_){ra.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");ra.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}"}this.svgObject=R(Na,null,{width:c+F,height:a+F,position:sa},b)}else this.svgObject=R("object",{width:c,height:a,type:"image/svg+xml"},{position:sa,left:0,top:0},b)}return this.svgObject},drawLine:function(a,b,c,d,e,f){var g=this.getCtx();if(a==c)a=c=N(a)+f%2/2;if(b==d)b=d=N(b)+f%2/2;g.lineWidth=f;g.lineCap=
"round";g.beginPath();g.moveTo(a,b);g.strokeStyle=e;g.lineTo(c,d);g.closePath();g.stroke()},drawPolyLine:function(a,b,c,d,e){var f=this.getCtx(),g=[];if(d&&c){o(a,function(h){g.push(h===ia?h:h+1)});for(d=1;d<=3;d++)this.drawPolyLine(g,"rgba(0, 0, 0, "+0.05*d+")",6-2*d)}f.beginPath();for(d=0;d<a.length;d+=2)f[d==0?"moveTo":"lineTo"](a[d],a[d+1]);K(f,{lineWidth:c,lineJoin:"round"});if(b&&c){f.strokeStyle=Ab(b,f);f.stroke()}if(e){f.fillStyle=Ab(e,f);f.fill()}},drawRect:function(a,b,c,d,e,f,g,h,j,m){var s=
function(){var z;if(c>0&&d>0){x.beginPath();if(g){x.moveTo(a,b+g);x.lineTo(a,b+d-g);x.quadraticCurveTo(a,b+d,a+g,b+d);x.lineTo(a+c-g,b+d);x.quadraticCurveTo(a+c,b+d,a+c,b+d-g);x.lineTo(a+c,b+g);x.quadraticCurveTo(a+c,b,a+c-g,b);x.lineTo(a+g,b);x.quadraticCurveTo(a,b,a,b+g)}else x.rect(a,b,c,d);x.closePath();z=true}return z},x=this.getCtx(),w=(f||0)%2/2;a=N(a)+w;b=N(b)+w;c=N(c-2*w);d=N(d-2*w);if(j)for(j=1;j<=3;j++)this.drawRect(a+1,b+1,c,d,"rgba(0, 0, 0, "+0.05*j+")",6-2*j,g);m&&x.drawImage(m,a,b,
c,d);if(s()){if(h){x.fillStyle=Ab(h,x);x.fill();Sa.G_vmlCanvasManager&&s()}if(f){x.strokeStyle=Ab(e,x);x.lineWidth=f;x.stroke()}}},drawSymbol:function(a,b,c,d,e,f,g){var h=this.getCtx(),j=/^url\((.*?)\)$/;h.beginPath();if(a=="square"){a=0.707*d;h.moveTo(b-a,c-a);h.lineTo(b+a,c-a);h.lineTo(b+a,c+a);h.lineTo(b-a,c+a);h.lineTo(b-a,c-a)}else if(a=="triangle"){c++;h.moveTo(b,c-1.33*d);h.lineTo(b+d,c+0.67*d);h.lineTo(b-d,c+0.67*d);h.lineTo(b,c-1.33*d)}else if(a=="triangle-down"){c--;h.moveTo(b,c+1.33*d);
h.lineTo(b-d,c-0.67*d);h.lineTo(b+d,c-0.67*d);h.lineTo(b,c+1.33*d)}else if(a=="diamond"){h.moveTo(b,c-d);h.lineTo(b+d,c);h.lineTo(b,c+d);h.lineTo(b-d,c);h.lineTo(b,c-d)}else j.test(a)?R("img",{onload:function(){var m=this,s=Fc[m.src]||[m.width,m.height];xa(m,{left:N(b-s[0]/2)+F,top:N(c-s[1]/2)+F,visibility:nc});Fc[m.src]=s},src:a.match(j)[1]},{position:sa,visibility:Ka?nc:Va},this.div):h.arc(b,c,d,0,2*wa.PI,true);if(g){h.fillStyle=g;h.fill()}if(f&&e){h.strokeStyle=f||"rgb(100, 100, 255)";h.lineWidth=
e||2;h.stroke()}},drawHtml:function(a,b,c){R(Na,K(b,{innerHTML:a}),K(c,{position:sa}),this.div)},drawText:function(){this.addText.apply(this,arguments);this.strokeText()},addText:function(a,b,c,d,e,f){if(a||a===0){var g=this,h,j=g.div,m,s="";d=d||{};var x=d.color||"#000000";f=f||"left";var w=parseInt(d.fontSize||d.font.replace(/^[a-z ]+/,""));for(var z in d)s+=Gb(z)+":"+d[z]+";";o(["MozTransform","WebkitTransform","transform"],function(pa){if(pa in j.style)m=pa});if(!e||m){a=R("span",{innerHTML:a},
K(d,{position:sa,left:b+F,whiteSpace:"nowrap",bottom:N(g.height-c-w*0.25)+F,color:x}),j);s=a.offsetWidth;if(f=="right")xa(a,{left:b-s+F});else f=="center"&&xa(a,{left:N(b-s/2)+F});if(e){f={left:0,center:50,right:100}[f];a.style[m]="rotate("+e+"deg)";a.style[m+"Origin"]=f+"% 100%"}}else if(Ka){h=true;d=(e||0)*wa.PI*2/360;e=$b(d);d=ac(d);z=g.width;w=w/3||3;var A=f=="left",S=f=="right",oa=A?b:b-z*e;b=S?b:b+z*e;A=A?c:c-z*d;c=S?c:c+z*d;oa+=w*d;b+=w*d;A-=w*e;c-=w*e;if(Aa(oa-b)<0.1)oa+=0.1;if(Aa(A-c)<0.1)A+=
0.1;g.svg+='<g_vml_:line from="'+oa+", "+A+'" to="'+b+", "+c+'" stroked="false"><g_vml_:fill on="true" color="'+x+'"/><g_vml_:path textpathok="true"/><g_vml_:textpath on="true" string="'+a+'" style="v-text-align:'+f+";"+s+'"/></g_vml_:line>'}else{h=true;g.svg+='<g><text transform="translate('+b+","+c+") rotate("+(e||0)+')" style="fill:'+x+";text-anchor:"+{left:"start",center:"middle",right:"end"}[f]+";"+s.replace(/"/g,"'")+'">'+a+"</text></g>"}g.hasObject=h}},strokeText:function(){if(this.hasObject){var a=
this.getSvg(),b=this.svg;if(Ka)a.innerHTML=b;else{a.data="data:image/svg+xml,"+b+"</svg>";Uc&&this.div.appendChild(a)}}},clear:function(){var a=this,b=this.div;b=b.childNodes;a.ctx&&a.ctx.clearRect(0,0,a.width,a.height);if(a.svgObject){za(a.svgObject);a.svgObject=null;a.svg=a.basicSvg}for(var c=b.length-1;c>=0;c--){a=b[c];a.tagName=="SPAN"&&za(a)}},hide:function(){xa(this.div,{display:"none"})},show:function(){xa(this.div,{display:""})},destroy:function(){za(this.div);return null}};var bc=function(){};
bc.prototype={init:function(a,b){var c=this;c.series=a;c.applyOptions(b);return c},applyOptions:function(a){var b=this,c=b.series;if(typeof a=="number"||a===null)b.y=a;else if(typeof a=="object"&&typeof a.length!="number"){K(b,a);b.options=a}else if(typeof a[0]=="string"){b.name=a[0];b.y=a[1]}else if(typeof a[0]=="number"){b.x=a[0];b.y=a[1]}if(b.x===ia)b.x=c.autoIncrement()},destroy:function(){var a=this;a.stateLayer&&a.stateLayer.destroy();for(prop in a)a[prop]=null},select:function(a,b){var c=this,
d=c.series,e=d.chart,f,g,h=ja(c.stateLayer,d.singlePointLayer,e.singlePointLayer);c.selected=a=ja(a,!c.selected);d.isDirty=true;c.firePointEvent(a?"select":"unselect");h&&h.clear();o(e.series,function(j){f=j.stateLayers;b||o(j.data,function(m){if(m.selected&&m!=c){m.selected=false;ka(m,"unselect");j.isDirty=true}});if(j.isDirty){for(g in f)f[g].clear();j.render()}})},update:function(a,b){var c=this,d=c.series;b=ja(b,true);c.firePointEvent("update",{options:a},function(){c.applyOptions(a);d.isDirty=
true;b&&d.chart.redraw()})},remove:function(a){var b=this,c=b.series,d=c.chart,e=c.data;a=ja(a,true);b.firePointEvent("remove",null,function(){o(e,function(f,g){f==b&&e.splice(g,1)});if(b.layer)b.layer=b.layer.destroy();if(b.legendItem){za(b.legendItem);b.legendItem=null;d.isDirty=true}c.isDirty=true;a&&d.redraw()})},firePointEvent:function(a,b,c){var d=this,e=this.series;e=e.options;if(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])this.importEvents();if(a=="click"&&e.allowPointSelect)c=
function(f){d.select(null,f.ctrlKey||f.metaKey||f.shiftKey)};ka(this,a,b,c)},importEvents:function(){if(!this.hasImportedEvents){var a=this,b=W(a.series.options.point,a.options);b=b.events;var c;a.events=b;for(c in b)Ia(a,c,b[c]);this.hasImportedEvents=true}},setTooltipText:function(){var a=this;a.tooltipText=a.series.chart.options.tooltip.formatter.call({series:a.series,point:a,x:a.category,y:a.y,percentage:a.percentage})}};var Ja=function(){this.isCartesian=true;this.type="line";this.pointClass=
bc};Ja.prototype={init:function(a,b){var c=this,d,e=a.series.length;c.chart=a;b=c.setOptions(b);K(c,{index:e,options:b,name:b.name||"Series "+(e+1),state:"",visible:b.visible!==false,selected:b.selected==true});a=b.events;for(d in a)Ia(c,d,a[d]);c.getColor();c.getSymbol();c.getData(b)},getData:function(a){var b=this,c=b.chart,d="series"+fc++;if(!a.data&&a.dataURL){c.addLoading(d);pc(a.dataURL,function(e){b.dataLoaded(e);c.clearLoading(d)})}else b.dataLoaded(a.data)},dataLoaded:function(a){var b=this,
c=b.chart,d=b.options,e=[""],f=d.dataParser,g={},h;if(d.dataURL&&!f)f=function(j){return eval(j)};if(f)a=f.call(b,a);b.layerGroup=h=new na("series-group",c.plotLayer.div,null,{zIndex:2});d.states.hover.enabled&&e.push("hover");o(e,function(j){g[j]=new na("state-"+j,h.div)});b.stateLayers=g;b.setData(a,false)},autoIncrement:function(){var a=this,b=a.options,c=a.xIncrement;c=ja(c,b.pointStart,0);a.pointInterval=ja(a.pointInterval,b.pointInterval,1);a.xIncrement=c+a.pointInterval;return c},cleanData:function(){var a=
this;a=a.data;var b;a.sort(function(c,d){return c.x-d.x});for(b=a.length-1;b>=0;b--)a[b-1]&&a[b-1].x==a[b].x&&a.splice(b-1,1)},getSegments:function(){var a=-1,b=[],c=this.data;o(c,function(d,e){if(d.y===null){e>a+1&&b.push(c.slice(a+1,e));a=e}else e==c.length-1&&b.push(c.slice(a+1,e+1))});this.segments=b},setOptions:function(a){var b=this.chart.options.plotOptions;a=W(b[this.type],b.series,a);b=a.marker;var c=a.states.hover.marker;if(c.lineWidth===ia)c.lineWidth=b.lineWidth+1;if(c.radius===ia)c.radius=
b.radius+1;return a},getColor:function(){var a=this.chart.options.colors;this.color=this.options.color||a[tb++]||"#0000ff";if(tb>=a.length)tb=0},getSymbol:function(){var a=this.chart.options.symbols,b=this.options.marker.symbol||"auto";if(b=="auto")b=a[Zb++];this.symbol=b;if(Zb>=a.length)Zb=0},addPoint:function(a,b,c){var d=this,e=d.data;a=(new d.pointClass).init(d,a);b=ja(b,true);e.push(a);c&&e.shift();d.isDirty=true;b&&d.chart.redraw()},setData:function(a,b){var c=this;c.xIncrement=null;a=jb(cc(a),
function(d){return(new c.pointClass).init(c,d)});c.data=a;c.cleanData();c.getSegments();c.isDirty=true;ja(b,true)&&c.chart.redraw()},remove:function(a){var b=this,c=b.chart;a=ja(a,true);if(!b.isRemoving){b.isRemoving=true;ka(b,"remove",null,function(){za(b.layerGroup.div);o(b.areas,function(d){za(d)});za(b.legendItem);b.legendItem=null;o(c.series,function(d,e){d==b&&c.series.splice(e,1)});c.isDirty=true;a&&c.redraw()})}b.isRemoving=false},translate:function(){var a=this.chart,b=this,c=b.options.stacking,
d=b.xAxis.categories,e=b.yAxis,f=e.stacks[b.type];o(this.data,function(g){var h=g.x,j=g.y,m;g.plotX=b.xAxis.translate(g.x);if(c){m=f[h];h=m.total;m.cum=m=m.cum-j;j=m+j;if(c=="percent"){m=h?m*100/h:0;j=h?j*100/h:0}g.percentage=h?g.y*100/h:0;g.stackTotal=h;g.yBottom=e.translate(m,0,1)}if(j!==null)g.plotY=e.translate(j,0,1);g.clientX=a.inverted?a.plotHeight-g.plotX+a.plotTop:g.plotX+a.plotLeft;g.category=d&&d[g.x]!==ia?d[g.x]:g.x})},setTooltipPoints:function(a){var b=this,c=b.chart,d=c.inverted,e=[],
f=d?c.plotHeight:c.plotWidth,g,h,j=[];if(a)b.tooltipPoints=null;o(b.segments,function(m){e=e.concat(m)});if(b.xAxis.reversed)e=e.reverse();o(e,function(m,s){b.tooltipPoints||m.setTooltipText();g=e[s-1]?e[s-1].high+1:0;for(h=m.high=e[s+1]?Qa((m.plotX+(e[s+1]?e[s+1].plotX:f))/2):f;g<=h;)j[d?f-g++:g++]=m});b.tooltipPoints=j},drawLine:function(a){var b=this,c=b.options,d=b.chart,e=c.animation&&b.animate,f=b.stateLayers[a],g=c.lineColor||b.color,h=c.fillColor=="auto"?qc(b.color).setOpacity(c.fillOpacity||
0.75).get():c.fillColor,j=d.inverted,m=(j?0:d.plotHeight)-b.yAxis.translate(0);if(a)c=W(c,c.states[a]);e&&b.animate(true);o(b.segments,function(s){var x=[],w=[];o(s,function(A){x.push(j?d.plotWidth-A.plotY:A.plotX,j?d.plotHeight-A.plotX:A.plotY)});if(/area/.test(b.type)){for(var z=0;z<x.length;z++)w.push(x[z]);if(c.stacking&&b.type!="areaspline")for(z=s.length-1;z>=0;z--)w.push(s[z].plotX,s[z].yBottom);else w.push(j?m:s[s.length-1].plotX,j?d.plotHeight-s[s.length-1].plotX:m,j?m:s[0].plotX,j?d.plotHeight-
s[0].plotX:m);f.drawPolyLine(w,null,null,c.shadow,h)}c.lineWidth&&f.drawPolyLine(x,g,c.lineWidth,c.shadow)});e&&b.animate()},animate:function(a){var b=this,c=b.chart,d=c.inverted,e=b.layerGroup.div;if(b.visible)if(a)xa(e,K({overflow:Va},d?{height:0}:{width:0}));else{vb(e,d?{height:c.plotHeight+F}:{width:c.plotWidth+F},{duration:1E3});this.animate=null}},drawPoints:function(a){var b=this,c=b.stateLayers[a];a=b.options;var d=a.marker;a=b.data;var e=b.chart,f=e.inverted;d.enabled&&o(a,function(g){if(g.plotY!==
ia)b.drawMarker(c,f?e.plotWidth-g.plotY:g.plotX,f?e.plotHeight-g.plotX:g.plotY,W(d,g.marker));g.selected&&b.drawPointState(g,"select",c)})},drawMarker:function(a,b,c,d){if(d.lineColor=="auto")d.lineColor=this.color;if(d.fillColor=="auto")d.fillColor=this.color;if(d.symbol=="auto")d.symbol=this.symbol;a.drawSymbol(d.symbol,b,c,d.radius,d.lineWidth,d.lineColor,d.fillColor)},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a=this,b,c,d=a.data,e=a.options.dataLabels,f,g,h=a.chart,j=h.inverted,
m=a.type,s=m=="pie",x;a.dataLabelsLayer=g=new na("data-labels",a.layerGroup.div,null,{zIndex:1});e.style.color=e.color=="auto"?a.color:e.color;o(d,function(w){var z=w.plotX,A=w.plotY,S=w.tooltipPos;f=e.formatter.call({x:w.x,y:w.y,series:a,point:w});b=(j?h.plotWidth-A:z)+e.x;c=(j?h.plotHeight-z:A)+e.y;if(S){b=S[0]+e.x;c=S[1]+e.y}if(s){if(!w.dataLabelsLayer)w.dataLabelsLayer=new na("data-labels",w.layer.div,null,{zIndex:3});g=w.dataLabelsLayer}x=e.align;if(m=="column")b+={center:w.w/2,right:w.w}[x]||
0;if(f)g[s?"drawText":"addText"](f,b,c,e.style,e.rotation,x)});s||g.strokeText()}},drawPointState:function(a,b,c){var d=this.chart,e=d.inverted,f=b=="hover";c=c||d.singlePointLayer;var g=this.options;if(f){if(!c)c=d.singlePointLayer=new na("single-point",d.plotLayer.div,null,{zIndex:3});c.clear()}if(b){var h=g.states[b].marker;b=g.marker.states[b];if(f&&b.radius===ia)b.radius=h.radius+2;if((f=W(g.marker,a.marker,h,b))&&f.enabled)this.drawMarker(c,e?d.plotWidth-a.plotY:a.plotX,e?d.plotHeight-a.plotX:
a.plotY,f)}},destroy:function(){var a=this,b;o(a.data,function(c){c.destroy()});for(b in a)a[b]=null},render:function(){var a=this,b,c=a.stateLayers;a.drawDataLabels();if(a.visible)for(b in c){a.drawLine(b);a.drawPoints(b)}else a.setVisible(false,false);if(!a.hasRendered&&c.hover){c.hover.hide();hasRendered=true}a.isDirty=false},redraw:function(){var a=this;a.translate();a.setTooltipPoints(true);a.chart.options.tooltip.enabled&&a.createArea();a.clear();a.render()},clear:function(){var a=this.stateLayers;
for(var b in a){a[b].clear();a[b].cleared=true}if(this.dataLabelsLayer){this.dataLabelsLayer.clear();this.hasDrawnDataLabels=false}},setState:function(a){a=a||"";if(this.state!=a){var b=this,c=b.stateLayers,d=c[a];c=c[b.state];var e=b.singlePointLayer||b.chart.singlePointLayer;b.state=a;if(d)if(a)d.show();else{c&&c.hide();e&&e.clear()}}},setVisible:function(a,b){var c=this,d=c.chart,e=c.layerGroup,f=c.legendItem,g=c.areas,h=c.visible;if(c.visible=a=a===ia?!h:a){c.isDirty=true;e.show()}else e.hide();
if(f){f.className=a?"":Fb;d.legend.drawGraphics(true)}g&&o(g,function(j){a?d.tracker.insertAtFront(j):za(j)});d.options.chart.ignoreHiddenSeries&&c.options.stacking&&o(d.series,function(j){if(j.options.stacking&&j.visible)j.isDirty=true});b!==false&&d.redraw();ka(c,a?"show":"hide")},show:function(){this.setVisible(true)},hide:function(){this.setVisible(false)},select:function(a){var b=this;b.selected=a=a===ia?!b.selected:a;if(b.checkbox)b.checkbox.checked=a;ka(b,a?"select":"unselect")},getAreaCoords:function(){var a=
this,b=this.chart,c=b.inverted,d=b.plotWidth,e=b.plotHeight,f=b.options.tooltip.snap,g=[];o(a.splinedata||a.segments,function(h,j){if(h.length>1&&h[0].x>h[1].x)h=reverseArray(h);var m=[],s=[],x=[];o([s,x],function(w){for(var z=0,A=0,S,oa,pa=[h[0]],Bb=w==s?1:-1,fb,ab,hb,ta,C,V,P;h[A];){if(h[A].plotX>h[z].plotX+f||A==h.length-1){S=h[A];oa=h.slice(z,A-1);o(oa,function(wb){if(Bb*wb.plotY<Bb*S.plotY)S=wb});if(N(h[z].plotX)<N(S.plotX)||h[A].plotX>h[z].plotX+f)pa.push(S);z=A}A++}pa[pa.length-1]!=h[h.length-
1]&&pa.push(h[h.length-1]);for(A=0;A<pa.length;A++)if(A>0){ab=pa[A].plotX;fb=pa[A].plotY;z=pa[A-1].plotX;oa=pa[A-1].plotY;ta=ab-pa[A-1].plotX;V=C=fb-pa[A-1].plotY;hb=-ta;P=wa.sqrt(wa.pow(V,2)+wa.pow(hb,2));if(A==1){z-=f/P*ta;oa-=f/P*C}else if(A==pa.length-1){ab+=f/P*ta;fb+=f/P*C}ta=Bb*f/P;z=N(z+ta*V);oa=N(oa+ta*hb);ab=N(ab+ta*V);hb=N(fb+ta*hb);if(w[w.length-1]&&w[w.length-1][0]>z)for(fb=false;!fb;){C=w.pop();V=w[w.length-1];if(!V)break;ta=(oa-hb)/(z-ab);C=(V[1]-C[1])/(V[0]-C[0]);C=(-C*V[0]+V[1]+ta*
z-oa)/(ta-C);ta=ta*(C-z)+oa;if(C>V[0]){w.push([N(C),N(ta),1]);fb=true}}else isNaN(z)||w.push([z,oa]);w[w.length-1]&&w[w.length-1][0]<ab&&w.push([ab,hb])}});for(j=0;j<s.length;j++)m.push(c?d-s[j][1]:s[j][0],c?e-s[j][0]:s[j][1]);for(j=x.length-1;j>=0;j--)m.push(c?d-x[j][1]:x[j][0],c?e-x[j][0]:x[j][1]);!m.length&&h[0]&&m.push(N(h[0].plotX),N(h[0].plotY));g.push([m.join(",")])});return g},createArea:function(){if(this.options.enableMouseTracking!==false){var a,b=this,c=b.options,d=b.chart,e=d.tracker,
f=b.getAreaCoords(),g=[],h=b.areas,j;h&&o(h,function(m){za(m)});o(f,function(m){j=/^[0-9]+,[0-9]+$/.test(m[0]);a=R("area",{shape:j?"circle":"poly",chart:d,coords:m[0]+(j?","+d.options.tooltip.snap:""),onmouseover:function(){if(!(!b.visible||d.mouseIsDown)){var s=d.hoverSeries;d.hoverPoint=m[1];c.events.mouseOver&&ka(b,"mouseOver",{point:d.hoverPoint});s&&s!=b&&s.setState();/(column|bar|pie)/.test(b.type)||e.insertAtFront(a);b.setState("hover");d.hoverSeries=b}},onmouseout:function(){var s=d.hoverSeries;
s&&c.events.mouseOut&&ka(s,"mouseOut")}});if(c.cursor=="pointer")a.href="javascript:;";e.insertAtFront(a);g.push(a)});b.areas=g}}};var Pc=db(Ja),Qc=db(Ja,{type:"area"}),Dc=db(Ja,{type:"spline",translate:function(){var a=this;Ja.prototype.translate.apply(a,arguments);a.splinedata=a.getSplineData()},drawLine:function(){var a=this,b=a.segments;a.segments=a.splinedata;Ja.prototype.drawLine.apply(a,arguments);a.segments=b},getSplineData:function(){var a=this,b=a.chart,c=[],d;o(a.segments,function(e){if(a.xAxis.reversed)e=
e.reverse();var f=[],g,h;o(e,function(j,m){g=e[m+2]||e[m+1]||j;h=e[m-2]||e[m-1]||j;g.plotX>0&&h.plotY<b.plotWidth&&f.push(j)});if(f.length>1)d=N(Ub(b.plotWidth,f[f.length-1].clientX-f[0].clientX)/3);c.push(e.length>1?d?(new Ec(f)).get(d):[]:e)});return a.splinedata=c}});Ec.prototype={get:function(a){a||(a=50);var b=this.n;b=(this.xdata[b-1]-this.xdata[0])/(a-1);var c=[],d=[];c[0]=this.xdata[0];d[0]=this.ydata[0];for(var e=[{plotX:c[0],plotY:d[0]}],f=1;f<a;f++){c[f]=c[0]+f*b;d[f]=this.interpolate(c[f]);
e[f]={plotX:c[f],plotY:d[f]}}return e},interpolate:function(a){for(var b=this.n-1,c=0;b-c>1;){var d=(b+c)/2;if(this.xdata[Qa(d)]>a)b=d;else c=d}b=Qa(b);c=Qa(c);d=this.xdata[b]-this.xdata[c];var e=(this.xdata[b]-a)/d;a=(a-this.xdata[c])/d;return e*this.ydata[c]+a*this.ydata[b]+((e*e*e-e)*this.y2[c]+(a*a*a-a)*this.y2[b])*d*d/6}};var Rc=db(Dc,{type:"areaspline"}),Lb=db(Ja,{type:"column",init:function(){Ja.prototype.init.apply(this,arguments);var a=this,b=a.chart;b.hasRendered&&o(b.series,function(c){if(c.type==
a.type)c.isDirty=true})},translate:function(){var a=this,b=a.chart,c=0,d;Ja.prototype.translate.apply(a);o(b.series,function(S){if(S.type==a.type)if(S.options.stacking){Ta(d)||(d=c++);S.columnIndex=d}else S.columnIndex=c++});var e=a.options,f=a.data,g=b.inverted,h=b.plotWidth,j=b.plotHeight,m=a.closestPoints;m=Aa(f[1]?f[m].plotX-f[m-1].plotX:g?j:h);var s=m*e.groupPadding,x=m-2*s;x=x/c;e=x*e.pointPadding;var w=x-2*e;b=(b.options.xAxis.reversed?c-a.columnIndex:a.columnIndex)||0;var z=-(m/2)+s+b*x+e,
A=a.yAxis.translate(0);o(f,function(S){S.plotX+=z;S.w=w;S.y0=(g?h:j)-A;S.h=(S.yBottom||S.y0)-S.plotY})},drawLine:function(){},getSymbol:function(){},drawPoints:function(a){var b=this,c=b.options,d=b.chart,e=c.animation&&b.animate,f=d.inverted,g=b.data,h=b.stateLayers[a];e&&this.animate(true);o(g,function(j){if(j.plotY!==ia)h.drawRect(f?j.h>=0?d.plotWidth-j.plotY-j.h:d.plotWidth-j.plotY:j.plotX,f?d.plotHeight-j.plotX-j.w:j.h>=0?j.plotY:j.plotY+j.h,f?Aa(j.h):j.w,f?j.w:Aa(j.h),c.borderColor,c.borderWidth,
c.borderRadius,j.color||b.color,c.shadow);j.selected&&b.drawPointState(j,"select",h)});e&&b.animate()},drawPointState:function(a,b,c){var d=this,e=d.chart,f=d.options,g=a?a.options:null,h=e.inverted;c=c||d.singlePointLayer;if(b=="hover"){if(!c)c=d.singlePointLayer=new na("single-point",d.layerGroup.div);c.clear()}if(b&&this.options.states[b]){b=W(f,f.states[b],g);c.drawRect(h?e.plotWidth-a.plotY-a.h:a.plotX,h?e.plotHeight-a.plotX-a.w:a.plotY,h?a.h:a.w,h?a.w:a.h,b.borderColor,b.borderWidth,b.borderRadius,
qc(b.color||this.color).brighten(b.brightness).get(),b.shadow)}},getAreaCoords:function(){var a=[],b=this.chart,c=b.inverted;o(this.data,function(d){var e=Ub(Aa(d.h),3)*(d.h<0?-1:1),f=c?b.plotWidth-d.plotY-e:d.plotX,g=c?b.plotHeight-d.plotX-d.w:d.plotY,h=g+(c?d.w:e);e=f+(c?e:d.w);if(!c&&Aa(e-f)<1)e=f+1;else if(c&&Aa(g-h)<1)g=h+1;a.push([jb([f,h,f,g,e,g,e,h],N).join(","),d])});return a},cleanData:function(){var a=this,b=a.data,c,d,e,f;Ja.prototype.cleanData.apply(a);for(f=b.length-1;f>=0;f--)if(b[f-
1]){c=b[f].x-b[f-1].x;if(d===ia||c<d){d=c;e=f}}a.closestPoints=e},animate:function(a){var b=this,c=b.chart,d=c.inverted,e=b.layerGroup.div;if(a)e.style[d?"left":"top"]=(d?-c.plotWidth:c.plotHeight)+F;else{vb(e,c.inverted?{left:0}:{top:0});b.animate=null}},remove:function(){var a=this,b=a.chart;b.hasRendered&&o(b.series,function(c){if(c.type==a.type)c.isDirty=true});Ja.prototype.remove.apply(a,arguments)}}),sc=db(Lb,{type:"bar",init:function(a){a.inverted=this.inverted=true;Lb.prototype.init.apply(this,
arguments)}}),Tc=db(Ja,{type:"scatter",getAreaCoords:function(){var a=this.data,b=[];o(a,function(c){b.push([[N(c.plotX),N(c.plotY)].join(","),c])});return b},cleanData:function(){}});O=db(bc,{setState:function(a){this.series.drawPointState(this,a)},init:function(){bc.prototype.init.apply(this,arguments);var a=this,b=a.series,c=b.chart.options.colors;K(a,{visible:a.visible!==false,name:ja(a.name,"Slice"),color:a.color||c[tb++]});if(tb>=c.length)tb=0;if(!a.layer)a.layer=new na("pie",b.layerGroup.div);
b=function(){a.slice()};Ia(a,"select",b);Ia(a,"unselect",b);return a},setVisible:function(a){var b=this,c=b.layer,d=b.legendItem;(b.visible=a=a===ia?!b.visible:a)?c.show():c.hide();if(d){d.className=a?"":Fb;b.series.chart.legend.drawGraphics(true)}},slice:function(a,b){var c=this,d=c.series;b=ja(b,true);c.sliced=Ta(a)?a:!c.sliced;d.isDirty=true;b&&d.chart.redraw()}});var Sc=db(Ja,{type:"pie",isCartesian:false,pointClass:O,getColor:function(){},translate:function(){var a=0,b=this,c=-0.25,d=b.options,
e=d.slicedOffset,f=d.center,g=b.chart;b=b.data;var h=2*wa.PI,j;f.push(d.size);f=jb(f,function(m,s){return/%$/.test(m)?g["plot"+(s?"Height":"Width")]*parseInt(m)/100:m});o(b,function(m){a+=m.y});o(b,function(m){j=a?m.y/a:0;m.start=c*h;c+=j;m.end=c*h;m.percentage=j*100;m.center=[f[0],f[1]];m.size=f[2];var s=(m.end+m.start)/2;m.centerSliced=jb([$b(s)*e+f[0],ac(s)*e+f[1]],N)});this.setTooltipPoints()},render:function(){this.drawPoints();this.drawDataLabels()},drawPoints:function(){var a=this;o(this.data,
function(b){a.drawPoint(b,b.layer.getCtx(),b.color);b.visible===false&&b.setVisible(false);b.selected&&a.drawPointState(b,"select",b.layer)})},getSymbol:function(){},drawPointState:function(a,b,c){var d=this,e=d.options;if(a){c=c||a.stateLayer;if(b=="hover"){if(!c)c=a.stateLayer=new na("single-point",a.layer.div);c.clear()}if(b&&d.options.states[b]){b=W(e,e.states[b]);this.drawPoint(a,c.getCtx(),b.color||a.color,b.brightness)}}d.hoverPoint&&d.hoverPoint.stateLayer&&d.hoverPoint.stateLayer.clear();
d.hoverPoint=a},drawPoint:function(a,b,c,d){var e=this.options,f=a.sliced?a.centerSliced:a.center,g=f[0];f=f[1];var h=a.size,j=e.borderWidth,m=Ka&&a.percentage==100?a.start:a.end;if(a.y>0){b.fillStyle=Ab(qc(c).brighten(d).get(b),b);b.strokeStyle=e.borderColor;b.lineWidth=j;b.beginPath();b.moveTo(g,f);b.arc(g,f,h/2,a.start,m,false);b.lineTo(g,f);b.closePath();b.fill();j&&b.stroke()}},getAreaCoords:function(){var a=[];o(this.data,function(b){for(var c=b.center[0],d=b.center[1],e=b.size/2,f=b.start,
g=b.end,h=[],j=f;j;j+=0.25){if(j>=g)j=g;h=h.concat([c+$b(j)*e,d+ac(j)*e]);if(j>=g)break}h=h.concat([c,d]);b.tooltipPos=[c+2*$b((f+g)/2)*e/3,d+2*ac((f+g)/2)*e/3];a.push([jb(h,N).join(","),b])});return a},clear:function(){o(this.data,function(a){a.layer.clear();a.dataLabelsLayer&&a.dataLabelsLayer.clear();a.stateLayer&&a.stateLayer.clear()})}});Highcharts={numberFormat:Hc,dateFormat:rc,setOptions:Gc,Chart:Ic}})();
